---

- name: "Install epel repository on hypervisor"
  yum:
    name: "{{ item }}"
    state: present
  loop: 
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: "Install packages required for overcloud deployment on hypervisor"
  yum:
    name: "{{ item }}"
    state: present
  loop: 
    - python2-pip
    - gcc
    - python-devel-2.7*

#pip install virtualbmc
#pip install --upgrade pip
- name: "Install virtualbmc"
  pip:
    name: virtualbmc

#virt-install --name ctrl01-overcloud.example.com --memory 16384 --vcpu 8 --cpu host --disk size=60,format=qcow2,bus=virtio --network bridge=virbr0,model=virtio --os-type=linux --pxe --noautoconsole
- name: "Create the VM Container from Dict"
  shell:
    cmd: "virt-install --name {{item.key}} \
          --memory {{item.value.memory}} \
          --vcpu {{item.value.cpu}} --cpu host \
          --disk size={{item.value.disk}},format=qcow2,bus=virtio \
          --network bridge={{item.value.network}},model=virtio \
          --os-type=linux --pxe --noautoconsole"
  with_dict: "{{OSP_NODES}}"

#vbmc add ctrl01-overcloud.example.com --port 6231 --username admin --password password
- name: "Create VMBC entries"
  shell:
    cmd: "vbmc add {{item.key}} --port {{item.value.vbmcport}}} --username {{OSP_VMBC_DEFAULT_USER}} --password {{OSP_VMBC_DEFAULT_PASS}}"
  with_dict: "{{OSP_NODES}}"

#vbmc start ctrl01-overcloud.example.com
- name: "Create VMBC entries"
  shell:
    cmd: "vbmc start {{item.key}}"
  with_dict: "{{OSP_NODES}}"